
services:
  backend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend

networks:
  ai-arena-network:
    driver: bridge