
services:
  backend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongodb
    networks:
      - ai-arena-network

  mongodb:
    image: mongo:7
    container_name: ai-arena-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-arena-network

volumes:
  mongodb_data:

networks:
  ai-arena-network:
    driver: bridge