services:
  - type: web
    name: ai-arena-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
